package com.wz.mapper;

import com.wz.model.Bstu;
import com.wz.model.BstuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BstuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_stu
     *
     * @mbggenerated
     */
    int countByExample(BstuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_stu
     *
     * @mbggenerated
     */
    int deleteByExample(BstuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_stu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_stu
     *
     * @mbggenerated
     */
    int insert(Bstu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_stu
     *
     * @mbggenerated
     */
    int insertSelective(Bstu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_stu
     *
     * @mbggenerated
     */
    List<Bstu> selectByExample(BstuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_stu
     *
     * @mbggenerated
     */
    Bstu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_stu
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Bstu record, @Param("example") BstuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_stu
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Bstu record, @Param("example") BstuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_stu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Bstu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_stu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Bstu record);
}